// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// eloDstC
NumericVector eloDstC(NumericVector rating, IntegerVector raceCount, NumericVector time, double K, double P, int provisionalN);
RcppExport SEXP skierELO_eloDstC(SEXP ratingSEXP, SEXP raceCountSEXP, SEXP timeSEXP, SEXP KSEXP, SEXP PSEXP, SEXP provisionalNSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type rating(ratingSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type raceCount(raceCountSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type provisionalN(provisionalNSEXP);
    __result = Rcpp::wrap(eloDstC(rating, raceCount, time, K, P, provisionalN));
    return __result;
END_RCPP
}
// eloSprC
NumericVector eloSprC(NumericVector rating, IntegerVector raceCount, double K, double P, int provisionalN);
RcppExport SEXP skierELO_eloSprC(SEXP ratingSEXP, SEXP raceCountSEXP, SEXP KSEXP, SEXP PSEXP, SEXP provisionalNSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type rating(ratingSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type raceCount(raceCountSEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type provisionalN(provisionalNSEXP);
    __result = Rcpp::wrap(eloSprC(rating, raceCount, K, P, provisionalN));
    return __result;
END_RCPP
}
// raceSimC
IntegerMatrix raceSimC(NumericVector ratings, int nsim);
RcppExport SEXP skierELO_raceSimC(SEXP ratingsSEXP, SEXP nsimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ratings(ratingsSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    __result = Rcpp::wrap(raceSimC(ratings, nsim));
    return __result;
END_RCPP
}
