# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eloDstC <- function(rating, raceCount, time, K, P, provisionalN) {
    .Call('skierELO_eloDstC', PACKAGE = 'skierELO', rating, raceCount, time, K, P, provisionalN)
}

eloSprC <- function(rating, raceCount, K, P, provisionalN) {
    .Call('skierELO_eloSprC', PACKAGE = 'skierELO', rating, raceCount, K, P, provisionalN)
}

raceSimC <- function(ratings, nsim) {
    .Call('skierELO_raceSimC', PACKAGE = 'skierELO', ratings, nsim)
}

